spring:
  servlet:
    multipart:
      max-file-size: 10MB  # Set to your required file size limit
      max-request-size: 10MB  # Set to your required request size limit
  datasource:
    url: jdbc:mysql://localhost:3306/Rasha_movie
    username: root
    password: Asd123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

server:
  port: 8080

omdb:
  api:
    key: e5588d2c
